[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]

[tool.ruff]
line-length = 120
target-version = "py311"
extend-ignore = ["I001"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C90", "N", "D"]
ignore = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.isort]
profile = "black"
line_length = 120
