name: Python CI

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify uv installation
      run: uv --version

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system \
          ruff mypy isort pytest pytest-cov \
          pydantic[mypy] pydantic-settings

    - name: Lint with Ruff
      run: ruff check .
      working-directory: ./server

    - name: Check formatting with Ruff
      run: ruff format --check .
      working-directory: ./server

    - name: Check import order with isort
      run: isort --check-only --diff .
      working-directory: ./server

    - name: Type check with Mypy
      run: mypy . --install-types --non-interactive

    - name: Run tests with Pytest
      run: pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=85
